server:
  port: 8443
  ssl: 
   key-store:  file:/Windows/System32/mykeys.jks 
   key-store-password: sssh9300662	
   key-password: sssh9300662

info: 
 contact: 
  email: support@myreadinglist.com 
  phone: 1-888-555-1971

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"
    shutdown:      enabled: true
   
amazon:
  associate_id: habuma-20
  
error:
  whitelabel:
    enabled: false
  
spring:
  profiles: 
   active: production
  main:
    banner-mode: 'off'
  thymeleaf:
    cache: false
---
spring: 
 profiles: development
logging: 
 level:
   root: DEBUG
   org.springframework.security: DEBUG
---
spring: 
 profiles: production   
logging: 
  path: /var/logs/ 
  file: BookWorm.log 
  level: 
    root: INFO
    org.springframework.security: INFO