server:
  port: 8443
  ssl: 
   key-store:  file:/Windows/System32/mykeys.jks 
   key-store-password: sssh9300662	
   key-password: sssh9300662
   
amazon:
  associate_id: habuma-20
  
error:
  whitelabel:
    enabled: false
  
spring:
  main:
    banner-mode: 'off'
  thymeleaf:
    cache: false

logging: 
  path: /var/logs/ 
  file: BookWorm.log 
  level: 
    root: INFO
    org.springframework.security: INFO
